SHOW DATABASES;
CREATE DATABASE STUDENT; 
USE STUDENT;

CREATE TABLE DEPARTMENT(
 DEPT_ID INT NOT NULL PRIMARY KEY,
 DEPT_NAME VARCHAR(40),
 CGPA INT
);

   CREATE TABLE STUDENTS (
   ID INT NOT NULL,
   CELL_ID INT,
   NAME VARCHAR (20) NOT NULL,
   AGE INT NOT NULL,
   ADDRESS CHAR (25),
   PRIMARY KEY (ID)
   FOREIGN KEY(DEPT_ID) REFERENECES DEPARTMENT(DEPT_ID) ON DELETE SET NULL
   );


 INSERT INTO STUDENTS VALUES(77,100,'pratham',23,'pune');
 INSERT INTO STUDENTS VALUES(78,200,'rajas',21,'boys hostel pune');
 INSERT INTO STUDENTS VALUES(3,300,'rudraksh',20,'pune');
 INSERT INTO STUDENTS VALUES(238,400,'prathamesh',20,'pune');
 INSERT INTO STUDENTS VALUES(216,200,'rohan',25,'pune');
 INSERT INTO STUDENTS VALUES(205,300,'Ravi',16,'pune');

INSERT INTO DEPARTMENT VALUES(100,'CSE',70);
INSERT INTO DEPARTMENT VALUES(200,'CSE',88);
INSERT INTO DEPARTMENT VALUES(300,'AI',84);
INSERT INTO DEPARTMENT VALUES(400,'AI',65);

SELECT * FROM STUDENTS;
SELECT * FROM DEPARTMENT;

-- //UPDATING THE ADDRESS OF THE STUDENT NAMED pratham.
UPDATE STUDENT
SET ADDRESS = 'Boys hostel pune'
WHERE ID = 77;

-- //CHANGE THE NAME OF THE STUDENT TABLE TO STUDENT_DETAILS.
ALTER TABLE STUDENT
RENAME TO STUDENT_DETAILS;

-- //ADD A NEW COLOUMN NAMED GENDER INTO THE STUDENT_DETAILS TABLE.
ALTER TABLE STUDENT_DETAILS
ADD GENDER VARCHAR(20);

-- //UPDATE THE AGE OF THE STUDENT NAMED KIRUBA IN THE STUDENT_DETAILS TABLE.
UPDATE STUDENT_DETAILS
SET AGE = 20
WHERE ID = 77;

-- //DISPLAY ALL THE STUDENTS AGE IN THE DESCENDING ORDER.
SELECT * FROM STUDENT_DETAILS ORDER BY AGE DESC;

-- //DISPLAYING THE NAME OF ALL THE STUDENTS
SELECT NAME FROM STUDENT_DETAILS;




-- // Using Thie Build in functions 
-- //1)Aggregate functions  -> Sum , Count , Avg , Max , min , varioande , std dev
-- //2) DAta and Time Functions
-- //3)Arithmatic functions ->
-- //4)Character functions ->
-- //5)cnoversionfunctions 
-- 6 muscellaneous funtions 




-- //USING AGGREGATE FUNCTIONS TO FIND THE COUNT OF THE STUDENTS FROM STUDENT_DETAILS TABLE
SELECT COUNT(ID) FROM STUDENT_DETAILS;

-- //DISPLAY THE AVERAGE OF CGPA'S FROM DEPARTMENT TABLE.
SELECT AVG(CGPA) FROM DEPARTMENT;

-- //DISPLAY THE DEPARTMENT ID OF MAXIMUM CGPA
SELECT MAX(CGPA) FROM DEPARTMENT;

-- //DISPLAY THE SUM of age for all Students
SELECT SUM(age) FROM STUDENT_DETAILS

-- // DISPLAY THE min of age for all the students
SELECT MIN(age) FROM STUDENT_DETAILS

-- // DISPLAY THE  of age for all the students
SELECT MIN(age) FROM STUDENT_DETAILS

-- //CREATING VIEWS 
CREATE VIEW STUDENT_INFO AS 
SELECT * FROM STUDENT_DETAILS WHERE AGE > 25;
SELECT * FROM STUDENT_INFO;

-- //DROPPING VIEWS 
DROP VIEW STUDENT_INFO;

-- //DROPPING THE DATABASE
DROP DATABASE STUDENT;


-- arithmatic functions 

GROUP by 
select dept Count from STUDENT_DETAILS
group by dept

select empname form emp data
WHERE